#!/bin/csh -f
# test one and do diff

set b = `basename ${2} .nex`
set dir = `dirname ${2}`

${SML} @SMLload=${1} ${dir}/${b}.nex >&! ${dir}/${b}.output
diff -wb ${dir}/${b}.correct ${dir}/${b}.output
rm ${dir}/${b}.output
